In [1]:
# Torch: The torch package contains data structures for multi-dimensional tensors
#        and mathmetical operations over these are defined.

In [2]:
# !pip install torch

In [3]:
import torch
import numpy as np

In [4]:
# 빈 텐서
x = torch.empty(5, 4)
print(x)

tensor([[1.0194e-38, 1.0469e-38, 1.0010e-38, 8.9081e-39],
        [8.9082e-39, 5.9694e-39, 8.9082e-39, 1.0194e-38],
        [9.1837e-39, 4.6837e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38, 1.0653e-38]])


In [5]:
# 1행렬
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# 0행렬
torch.zeros(2)

tensor([0., 0.])

In [7]:
# 랜덤행렬
torch.rand(5,6)

tensor([[0.5540, 0.1238, 0.8196, 0.5487, 0.1838, 0.4878],
        [0.3761, 0.5621, 0.8239, 0.8958, 0.5342, 0.1271],
        [0.3361, 0.7198, 0.7261, 0.5533, 0.9572, 0.8538],
        [0.8971, 0.5290, 0.5905, 0.7497, 0.8685, 0.5526],
        [0.6781, 0.4215, 0.0767, 0.8817, 0.8036, 0.1533]])

In [8]:
l = [13, 4]
r = np.array([4,56,7])

In [9]:
# list -> tensor
torch.tensor(l)

tensor([13,  4])

In [10]:
# 사이즈 확인
x.size()

torch.Size([5, 4])

In [11]:
# 타입 확인
type(x)

torch.Tensor

In [12]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.6505, 0.9128],
        [0.4581, 0.9528]])
tensor([[0.8784, 0.3737],
        [0.9153, 0.8759]])


In [13]:
# 연산자를 이용한 연산
x+y

tensor([[1.5289, 1.2865],
        [1.3734, 1.8288]])

In [14]:
# torch 함수를 이용한 연산
torch.add(x, y)

tensor([[1.5289, 1.2865],
        [1.3734, 1.8288]])

In [15]:
# y에 x를 더해서 값을 출력
y.add(x) # 실행 시 y값 변화 없음

tensor([[1.5289, 1.2865],
        [1.3734, 1.8288]])

In [16]:
# y에 x를 더해서 y를 대체
y.add_(x) # 실행 시 y값이 바뀜

tensor([[1.5289, 1.2865],
        [1.3734, 1.8288]])

In [17]:
# 1행 1열 표현
y[1,1]

tensor(1.8288)

In [18]:
# 1열 표현
y[:, 1]

tensor([1.2865, 1.8288])

In [19]:
# 8X8 행렬 생성
a = torch.rand(8,8)
print(a)

tensor([[0.8377, 0.3367, 0.2006, 0.0453, 0.0502, 0.7899, 0.5680, 0.2760],
        [0.2156, 0.6490, 0.5689, 0.0198, 0.1344, 0.0632, 0.4114, 0.2970],
        [0.1975, 0.2651, 0.8659, 0.5796, 0.0027, 0.4368, 0.6817, 0.2538],
        [0.6860, 0.9266, 0.4845, 0.9783, 0.6728, 0.4344, 0.9772, 0.8213],
        [0.1747, 0.9691, 0.7823, 0.8948, 0.4168, 0.0413, 0.9478, 0.6606],
        [0.3847, 0.9760, 0.6244, 0.2190, 0.4721, 0.0152, 0.2228, 0.6633],
        [0.1380, 0.3732, 0.5322, 0.0387, 0.4681, 0.0921, 0.2032, 0.8709],
        [0.0265, 0.9429, 0.5066, 0.9157, 0.0505, 0.5364, 0.4557, 0.3892]])


In [20]:
# tensor 표시 방법 1
a.view(64) # 열 기준으로 나열

tensor([0.8377, 0.3367, 0.2006, 0.0453, 0.0502, 0.7899, 0.5680, 0.2760, 0.2156,
        0.6490, 0.5689, 0.0198, 0.1344, 0.0632, 0.4114, 0.2970, 0.1975, 0.2651,
        0.8659, 0.5796, 0.0027, 0.4368, 0.6817, 0.2538, 0.6860, 0.9266, 0.4845,
        0.9783, 0.6728, 0.4344, 0.9772, 0.8213, 0.1747, 0.9691, 0.7823, 0.8948,
        0.4168, 0.0413, 0.9478, 0.6606, 0.3847, 0.9760, 0.6244, 0.2190, 0.4721,
        0.0152, 0.2228, 0.6633, 0.1380, 0.3732, 0.5322, 0.0387, 0.4681, 0.0921,
        0.2032, 0.8709, 0.0265, 0.9429, 0.5066, 0.9157, 0.0505, 0.5364, 0.4557,
        0.3892])

In [21]:
# tensor 표시 방법 2
a.view(-1, 4, 4)

tensor([[[0.8377, 0.3367, 0.2006, 0.0453],
         [0.0502, 0.7899, 0.5680, 0.2760],
         [0.2156, 0.6490, 0.5689, 0.0198],
         [0.1344, 0.0632, 0.4114, 0.2970]],

        [[0.1975, 0.2651, 0.8659, 0.5796],
         [0.0027, 0.4368, 0.6817, 0.2538],
         [0.6860, 0.9266, 0.4845, 0.9783],
         [0.6728, 0.4344, 0.9772, 0.8213]],

        [[0.1747, 0.9691, 0.7823, 0.8948],
         [0.4168, 0.0413, 0.9478, 0.6606],
         [0.3847, 0.9760, 0.6244, 0.2190],
         [0.4721, 0.0152, 0.2228, 0.6633]],

        [[0.1380, 0.3732, 0.5322, 0.0387],
         [0.4681, 0.0921, 0.2032, 0.8709],
         [0.0265, 0.9429, 0.5066, 0.9157],
         [0.0505, 0.5364, 0.4557, 0.3892]]])

In [22]:
# tensor -> numpy
b = a.numpy()
print(b)

[[0.8377312  0.3367154  0.20057231 0.04532957 0.05020303 0.78988516
  0.568021   0.2759533 ]
 [0.21561962 0.6489547  0.56890965 0.01976871 0.13435751 0.06316942
  0.41144216 0.2970323 ]
 [0.19750494 0.26508856 0.8659486  0.579644   0.00267243 0.4367538
  0.68167424 0.25379193]
 [0.6860097  0.9265735  0.48454863 0.9783334  0.67280143 0.43437916
  0.9772309  0.8212767 ]
 [0.1747114  0.96907455 0.78231394 0.89478284 0.41675276 0.04127115
  0.94781107 0.6605917 ]
 [0.38465822 0.9760212  0.6244202  0.2190404  0.4720993  0.01516771
  0.22278613 0.6633016 ]
 [0.13797677 0.3732016  0.5322015  0.03871167 0.4681087  0.09210902
  0.2032336  0.8709276 ]
 [0.02653146 0.94293064 0.5066166  0.91565037 0.05047411 0.5364341
  0.4557045  0.38924396]]


In [23]:
z = torch.ones(1) # 1행렬 z

In [24]:
z # tensor

tensor([1.])

In [25]:
# tensor 안의 값 출력
z.item() # value

1.0